# Generated by Django 4.2.6 on 2023-11-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscribtion',
            name='client',
        ),
        migrations.RemoveField(
            model_name='emailsubscribtion',
            name='email_filling',
        ),
        migrations.RemoveField(
            model_name='emailsubscribtionlogs',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='EmailFilling',
        ),
        migrations.DeleteModel(
            name='EmailSubscribtion',
        ),
        migrations.DeleteModel(
            name='EmailSubscribtionLogs',
        ),
    ]
