# Generated by Django 4.2.6 on 2023-10-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desc',
        ),
    ]
