# Generated by Django 4.2.6 on 2023-10-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons', models.TextField(verbose_name='обращение')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('feedback_anons', models.TextField(verbose_name='заполнение формы')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
