# Generated by Django 4.2.6 on 2023-11-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='entry_img',
            field=models.ImageField(blank=True, null=True, upload_to='entry_img/', verbose_name='изображение'),
        ),
    ]
