# Generated by Django 4.2.6 on 2023-11-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blogentry_entry_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogEntry',
        ),
    ]
