# Generated by Django 4.2.6 on 2023-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_blogentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
