# Generated by Django 4.2.6 on 2023-11-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_client_emailfilling_emailsubscribtion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscribtionlogs',
            options={'verbose_name': 'лог рассылки', 'verbose_name_plural': 'логи рассылки'},
        ),
    ]
