# Generated by Django 4.2.6 on 2023-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/', verbose_name='изображение категории'),
        ),
    ]
