# Generated by Django 4.2.6 on 2023-11-30 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('full_name', models.CharField(max_length=450, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='обладатель клиента')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='EmailFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template_name', models.CharField(max_length=120, verbose_name='название темплейта')),
                ('email_subject', models.CharField(max_length=300, verbose_name='тема письма')),
                ('email_body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'наполнение письма',
                'verbose_name_plural': 'наполнения писем',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время рассылки')),
                ('periodic_time', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=100, verbose_name='периодичность')),
                ('status', models.CharField(max_length=50, verbose_name='статус рассылки')),
                ('next_send_date', models.DateField(blank=True, null=True, verbose_name='дата следующей отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_distribution.client', verbose_name='клиент')),
                ('email_filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_distribution.emailfilling', verbose_name='наполнение письма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscribtionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('is_success', models.BooleanField(default=True, verbose_name='статус попытки')),
                ('last_mail_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_distribution.emailsubscribtion', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
    ]
