# Generated by Django 4.2.6 on 2023-12-01 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfilling',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель темплейта'),
        ),
    ]
