# Generated by Django 4.2.6 on 2023-12-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0002_emailfilling_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscribtion',
            name='is_enabled',
            field=models.CharField(choices=[('enabled', 'Включить'), ('disabled', 'Выключено')], default='enabled', max_length=50, verbose_name='Включить рассылку'),
            preserve_default=False,
        ),
    ]
