# Generated by Django 4.2.6 on 2023-12-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0004_alter_emailsubscribtionlogs_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscribtion',
            name='next_send_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата следующей отправки'),
        ),
        migrations.AlterField(
            model_name='emailsubscribtion',
            name='status',
            field=models.CharField(default='idle', max_length=50, verbose_name='статус рассылки'),
        ),
    ]
